print("Hey, man! What's up?")
response = input()
print('Awesome. Hey, by the way, what is your favorite game?')
game = input()
print('Wait, what? You like ' + game + '? I hate ' + game)
print('Why do you even like ' + game + '?')
reason = input()
print('Because ' + reason + '? Oh my gosh. Why do I even talk to you.')
print('We are no longer friends. Goodbye')
print('*Your only friend has logged off*')
