print('What element of powder?')
pw = input()
print('Enter amount of Tier I powder')
tone = input()
print('Enter amount of Tier II powder')
ttwo = input()
print('Enter amount of Tier III powder')
tthree = input()
print('Enter amount of Tier IV powder')
tfour = input()
print('Enter amount of Tier V powder')
tfive = input()
print('Enter amount of Tier VI powder')
tsix = input()
print('You have ' + str(int(tone) + 4*int(ttwo) + 4*4*int(tthree) + 4*4*4*int(tfour) + 4*4*4*4*int(tfive) + 4*4*4*4*4*int(tsix)) + ' tier I powder worth of ' + str(pw) + ' powder.')

